In [46]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
df =  pd.read_parquet("all_teams_last10seasons_with_opponent_rolls.parquet")

In [47]:
target = 'TARGET_WL'
exclude_cols = [
    'Team_ID',      # Note: case-sensitive
    'Team_ID_opp',  # Also exclude opponent ID
    'Game_ID',      # Note: case-sensitive
    target
]

# Create features list by excluding the right columns
features = [col for col in df.columns if col not in exclude_cols]

In [48]:
df_model = df.dropna(subset=features + [target])

# Split chronologically (e.g., 80% train, 20% test)
split_idx = int(len(df_model) * 0.8)
train_df = df_model.iloc[:split_idx]
test_df = df_model.iloc[split_idx:]

X_train = train_df[features]
y_train = train_df[target]
X_test = test_df[features]
y_test = test_df[target]

In [49]:
bool_cols = X_train.select_dtypes(include=['bool']).columns
if len(bool_cols) > 0:
    X_train[bool_cols] = X_train[bool_cols].astype(int)
    X_test[bool_cols] = X_test[bool_cols].astype(int)

/var/folders/14/drwtsk3n2wvdsmw2rj7tqh040000gn/T/ipykernel_10867/2585570748.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[bool_cols] = X_train[bool_cols].astype(int)
/var/folders/14/drwtsk3n2wvdsmw2rj7tqh040000gn/T/ipykernel_10867/2585570748.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[bool_cols] = X_test[bool_cols].astype(int)


## Baseline Logistic Regression Model

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import statsmodels.api as sm

# --- 1. Final tuned Logistic Regression pipeline ---
final_log_model = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(
        max_iter=2000,
        penalty='l1',       # tuned best param
        C=0.01,             # tuned best param
        solver='saga',      # tuned best param
        l1_ratio=0          # tuned best param (only for elasticnet, saga allows l1)
    ))
])

# Fit on training data
final_log_model.fit(X_train, y_train)

# Predict on test data
y_pred_log = final_log_model.predict(X_test)

# --- 2. Print standard metrics ---
print("\n=== Logistic Regression (tuned) Metrics ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred_log), 3))
print("Precision (macro):", round(precision_score(y_test, y_pred_log, average='macro'), 3))
print("Recall (macro):", round(recall_score(y_test, y_pred_log, average='macro'), 3))
print("F1-score (macro):", round(f1_score(y_test, y_pred_log, average='macro'), 3))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))

# --- 3. Optional: statsmodels Logit for AIC/BIC and coefficients ---
X_train_sm = sm.add_constant(X_train)
X_test_sm = sm.add_constant(X_test)

sm_model = sm.Logit(y_train, X_train_sm).fit()

y_proba_sm = sm_model.predict(X_test_sm)
y_pred_sm = (y_proba_sm >= 0.5).astype(int)

print("\nAIC:", sm_model.aic.round(2))
print("BIC:", sm_model.bic.round(2))

/Users/joshuademontigny/Downloads/ML_NBA_Project/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(



=== Logistic Regression (tuned) Metrics ===
Accuracy: 0.639
Precision (macro): 0.625
Recall (macro): 0.628
F1-score (macro): 0.626

Confusion Matrix:
 [[821 385]
 [330 447]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.68      0.70      1206
           1       0.54      0.58      0.56       777

    accuracy                           0.64      1983
   macro avg       0.63      0.63      0.63      1983
weighted avg       0.64      0.64      0.64      1983

Optimization terminated successfully.
         Current function value: 0.647516
         Iterations 10

AIC: 10374.89
BIC: 10737.78


## Baseline SVM

In [51]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# --- SVM (tuned) ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_model = SVC(
    C=1,
    gamma=0.001,
    kernel='rbf',
    probability=True,
    random_state=42
)

svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

print("\n=== SVM (tuned) ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred_svm), 3))
print("Precision (macro):", round(precision_score(y_test, y_pred_svm, average='macro'), 3))
print("Recall (macro):", round(recall_score(y_test, y_pred_svm, average='macro'), 3))
print("F1-score (macro):", round(f1_score(y_test, y_pred_svm, average='macro'), 3))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))


=== SVM (tuned) ===
Accuracy: 0.634
Precision (macro): 0.619
Recall (macro): 0.621
F1-score (macro): 0.619

Confusion Matrix:
 [[822 384]
 [342 435]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.68      0.69      1206
           1       0.53      0.56      0.55       777

    accuracy                           0.63      1983
   macro avg       0.62      0.62      0.62      1983
weighted avg       0.64      0.63      0.64      1983



## Baseline Random Forrest 

In [52]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# --- Random Forest (tuned) ---
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=4,
    class_weight=None,
    random_state=42
)

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("\n=== Random Forest (tuned) ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred_rf), 3))
print("Precision (macro):", round(precision_score(y_test, y_pred_rf, average='macro'), 3))
print("Recall (macro):", round(recall_score(y_test, y_pred_rf, average='macro'), 3))
print("F1-score (macro):", round(f1_score(y_test, y_pred_rf, average='macro'), 3))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))


=== Random Forest (tuned) ===
Accuracy: 0.634
Precision (macro): 0.621
Recall (macro): 0.624
F1-score (macro): 0.622

Confusion Matrix:
 [[810 396]
 [329 448]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.67      0.69      1206
           1       0.53      0.58      0.55       777

    accuracy                           0.63      1983
   macro avg       0.62      0.62      0.62      1983
weighted avg       0.64      0.63      0.64      1983



## XGBoost

In [54]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import accuracy_score, roc_auc_score

XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/Users/joshuademontigny/Downloads/ML_NBA_Project/.venv/lib/python3.12/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <636BF463-1886-392D-B8B3-6011C44DCEE9> /Users/joshuademontigny/Downloads/ML_NBA_Project/.venv/lib/python3.12/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)"]


In [ ]:
import os
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# --- Ensure output folder exists ---
output_folder = "tables"
os.makedirs(output_folder, exist_ok=True)

# --- Collect all model metrics ---
results = []

# Logistic Regression (tuned)
results.append({
    "model": "Logistic Regression (tuned)",
    "accuracy": round(accuracy_score(y_test, y_pred_log), 2),
    "precision": round(precision_score(y_test, y_pred_log, average='macro'), 2),
    "recall": round(recall_score(y_test, y_pred_log, average='macro'), 2),
    "f1_score": round(f1_score(y_test, y_pred_log, average='macro'), 2)
})

# SVM (tuned)
results.append({
    "model": "SVM (tuned)",
    "accuracy": round(accuracy_score(y_test, y_pred_svm), 2),
    "precision": round(precision_score(y_test, y_pred_svm, average='macro'), 2),
    "recall": round(recall_score(y_test, y_pred_svm, average='macro'), 2),
    "f1_score": round(f1_score(y_test, y_pred_svm, average='macro'), 2)
})

# Random Forest (tuned)
results.append({
    "model": "Random Forest (tuned)",
    "accuracy": round(accuracy_score(y_test, y_pred_rf), 2),
    "precision": round(precision_score(y_test, y_pred_rf, average='macro'), 2),
    "recall": round(recall_score(y_test, y_pred_rf, average='macro'), 2),
    "f1_score": round(f1_score(y_test, y_pred_rf, average='macro'), 2)
})

# --- Convert to DataFrame and save ---
comparison_table = pd.DataFrame(results)
comparison_table.to_csv(os.path.join(output_folder, "model_comparison.csv"), index=False)

print("✅ Model comparison table saved to tables/model_comparison.csv")
print(comparison_table)

✅ Model comparison table saved to tables/model_comparison.csv
                         model  accuracy  precision  recall  f1_score
0  Logistic Regression (tuned)      0.64       0.63    0.63      0.63
1                  SVM (tuned)      0.63       0.62    0.62      0.62
2        Random Forest (tuned)      0.63       0.62    0.62      0.62


In [ ]:
# --- SOFT VOTING ENSEMBLE ---
# Get predicted probabilities from each model
y_proba_log = final_log_model.predict_proba(X_test)
y_proba_svm = svm_model.predict_proba(X_test_scaled)
y_proba_rf = rf_model.predict_proba(X_test)

# ---- 1️⃣ Simple average (soft voting) ----
avg_proba = (y_proba_log + y_proba_svm + y_proba_rf) / 3
y_pred_ensemble_soft = np.argmax(avg_proba, axis=1)

# Compute metrics
soft_result = {
    "model": "Ensemble Soft Voting",
    "accuracy": round(accuracy_score(y_test, y_pred_ensemble_soft), 2),
    "precision": round(precision_score(y_test, y_pred_ensemble_soft, average='macro'), 2),
    "recall": round(recall_score(y_test, y_pred_ensemble_soft, average='macro'), 2),
    "f1_score": round(f1_score(y_test, y_pred_ensemble_soft, average='macro'), 2)
}

# ---- 2️⃣ Weighted soft voting ----
weights = [0.3, 0.2, 0.5]  # Adjust based on validation performance
weighted_avg_proba = (weights[0]*y_proba_log + weights[1]*y_proba_svm + weights[2]*y_proba_rf) / sum(weights)
y_pred_ensemble_weighted = np.argmax(weighted_avg_proba, axis=1)

weighted_result = {
    "model": "Ensemble Weighted Soft Voting",
    "accuracy": round(accuracy_score(y_test, y_pred_ensemble_weighted), 2),
    "precision": round(precision_score(y_test, y_pred_ensemble_weighted, average='macro'), 2),
    "recall": round(recall_score(y_test, y_pred_ensemble_weighted, average='macro'), 2),
    "f1_score": round(f1_score(y_test, y_pred_ensemble_weighted, average='macro'), 2)
}

# --- Remove any previous ensemble entries if rerunning ---
results = [r for r in results if "Ensemble" not in r["model"]]

# --- Append new ensemble results ---
results.extend([soft_result, weighted_result])

# --- Convert to DataFrame and save ---
comparison_table = pd.DataFrame(results)
comparison_table.to_csv(os.path.join(output_folder, "model_comparison.csv"), index=False)

print("✅ Updated model comparison table saved to tables/model_comparison.csv")
print(comparison_table)

✅ Updated model comparison table saved to tables/model_comparison.csv
                           model  accuracy  precision  recall  f1_score
0    Logistic Regression (tuned)      0.64       0.63    0.63      0.63
1                    SVM (tuned)      0.63       0.62    0.62      0.62
2          Random Forest (tuned)      0.63       0.62    0.62      0.62
3           Ensemble Soft Voting      0.64       0.62    0.63      0.62
4  Ensemble Weighted Soft Voting      0.64       0.63    0.63      0.63
